import { STATUS_LABEL, formatWhen, type Inspection } from "./inspections";

const esc = (value: string) =>
  value.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] ?? c);

/** Opens a print-ready inspection report; the browser print dialog saves it as PDF. */
export function openInspectionPdf(inspection: Inspection) {
  const rows = inspection.checks
    .map(
      (c) => `<tr>
        <td>${esc(c.label)}</td>
        <td>${esc(c.value ?? "Not declared / illegible")}</td>
        <td class="${c.status}">${c.status === "pass" ? "Compliant" : c.status === "fail" ? "Violation" : "Review"}</td>
        <td class="rule">${esc(c.rule)}</td>
      </tr>`,
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8" />
<title>Inspection ${esc(inspection.id)} — PackMetrix AI</title>
<style>
  body{font-family:Roboto,Arial,sans-serif;color:#1a1a1a;margin:32px;font-size:12px}
  h1{font-size:18px;color:#1565C0;margin:0}
  h2{font-size:13px;margin:24px 0 8px}
  .sub{font-size:11px;color:#555;margin-top:4px}
  table{width:100%;border-collapse:collapse;margin-top:8px}
  th,td{border:1px solid #d5d9e0;padding:6px 8px;text-align:left;vertical-align:top}
  th{background:#eef4fc;font-size:11px}
  .rule{color:#555;font-size:10px}
  .pass{color:#1b7d3f;font-weight:600}
  .fail{color:#c62828;font-weight:600}
  .warn{color:#b26a00;font-weight:600}
  .score{font-size:22px;font-weight:700;color:#1565C0}
  pre{white-space:pre-wrap;background:#f6f8fb;border:1px solid #d5d9e0;padding:8px;font-size:11px}
  img{max-width:220px;border:1px solid #d5d9e0;margin-top:8px}
</style></head><body>
<h1>Legal Metrology Inspection Report</h1>
<div class="sub">Ministry of Consumer Affairs, Food &amp; Public Distribution · PackMetrix AI</div>
<h2>Inspection details</h2>
<table>
  <tr><th>Inspection ID</th><td>${esc(inspection.id)}</td><th>Date &amp; time</th><td>${esc(formatWhen(inspection.createdAt))}</td></tr>
  <tr><th>Product</th><td>${esc(inspection.fields.productName ?? "Not declared")}</td><th>Premises</th><td>${esc(inspection.place)}</td></tr>
  <tr><th>Outcome</th><td>${esc(STATUS_LABEL[inspection.status])}</td><th>Compliance score</th><td class="score">${inspection.score}/100</td></tr>
</table>
<h2>Mandatory declarations</h2>
<table><thead><tr><th>Declaration</th><th>Extracted value</th><th>Status</th><th>Provision</th></tr></thead><tbody>${rows}</tbody></table>
<h2>Inspector remarks</h2>
<p>${esc(inspection.remarks)}</p>
<h2>Extracted label text</h2>
<pre>${esc(inspection.rawText || "No text extracted.")}</pre>
${inspection.imageDataUrl ? `<h2>Captured label</h2><img src="${inspection.imageDataUrl}" alt="Captured package label" />` : ""}
<p class="sub">Generated by PackMetrix AI under the Legal Metrology (Packaged Commodities) Rules, 2011.</p>
<script>window.onload=function(){window.print()}</script>
</body></html>`;

  const win = window.open("", "_blank");
  if (!win) return false;
  win.document.write(html);
  win.document.close();
  return true;
}
